### ISSUE TITLE
Neustes Update Funktioniert nicht

### ISSUE THREAD

**Issue by PommesTC** [PArns/ioBroker.innogy-smarthome#50]
Hallo

Wollte gerade den Innogy Adapter das neueste Update verpassen. Sagt auch das alles geklappt hat. Aber dann beim aktuallisieren wird das gleiche Update wieder angezeigt. Die jetzige Version lässt sich dann auch nicht mehr mit Smarthome verbinden.

Gruß

Thomas

---

**System data:**

Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
Model: Common KVM processor
RAM: 2.94 GB
Node.js: v12.18.1
NPM: 6.14.5
JS-Controller (1): 3.1.6
Admin: 4.1.1
Innogy Smarthome Adapter: 0.3.4

> *created by ioBroker.info*

**Comment by coldfusion75** [comment]
Hallo zusammen, ich kann das Update leider auch nicht installieren. Selbst mit Einstellung latest funktioniert hier nichts.
Danke und Gruss, Karsten

**Comment by JBSullivan** [comment]
Bei mir geht auch nichts mehr, nach dem Update auf 0.3.5 - aber auch schon vorher nicht unter 0.3.4 weil Innogy in der Nacht von Sonntag auf Montag am Backend rumgespielt hat.

EDIT: Sehe gerade, das der 0.3.5 sich gar nicht installieren läßt. Hängt bestimmt mit den verschärften Richtlinien von ioB zusammen. Leider wurde beim Innogy Adapter ja "vergessen" sich der Weiterentwicklung von ioB zu öffnen und den Adapter zu Community Weiterentwicklung frei zu geben. Auch Sentry wurde nicht implementiert.

![2020-06-30 11_55_48-instances - ioBroker](https://user-images.githubusercontent.com/44617472/86112930-e10a5e00-bac8-11ea-9fa8-7a047a704c49.png)

**Comment by coldfusion75** [comment]
@JBSullivan wie hast du denn das Update auf 0.3.5 hinbekommen?

**Comment by JBSullivan** [comment]
Gar nicht - habe mich vertan - siehe oben.

**Comment by JBSullivan** [comment]
`

innogy-smarthome.0 | 2020-06-30 12:06:01.638 | warn | (8184) Adapter is not connected ... Will recheck in 30 seconds!
-- | -- | -- | --
innogy-smarthome.0 | 2020-06-30 12:01:01.645 | warn | (8184) DEBUG: {"server":{"_events":{},"_eventsCount":2,"_maxListeners":100,"_connections":0,"_handle":{"reading":false},"_usingWorkers":false,"_workers":[],"_unref":false,"allowHalfOpen":true,"pauseO
innogy-smarthome.0 | 2020-06-30 12:01:01.645 | warn | (8184) Adapter is not configured or needs reauthorization! Please go to the adapter settings and start the authorization
innogy-smarthome.0 | 2020-06-30 12:01:01.607 | info | (8184) starting. Version 0.3.5 in C:/iobroker/GLT/node_modules/iobroker.innogy-smarthome, node: v12.18.0, js-controller: 3.1.6
host.Server(GLT) | 2020-06-30 12:00:59.819 | info | instance system.adapter.innogy-smarthome.0 started with pid 8184
host.Server(GLT) | 2020-06-30 12:00:29.807 | info | Restart adapter system.adapter.innogy-smarthome.0 because enabled
host.Server(GLT) | 2020-06-30 12:00:29.806 | info | instance system.adapter.innogy-smarthome.0 terminated with code 0 (NO_ERROR)
innogy-smarthome.0 | 2020-06-30 12:00:29.289 | info | (3816) Terminated (NO_ERROR): Without reason
innogy-smarthome.0 | 2020-06-30 12:00:29.289 | info | (3816) terminating
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at C:\iobroker\GLT\node_modules\standard-as-callback\built\index.js:19:49
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at tryCatcher (C:\iobroker\GLT\node_modules\standard-as-callback\built\utils.js:11:23)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at C:\iobroker\GLT\node_modules\iobroker.js-controller\lib\states\statesInRedis.js:616:17
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at C:\iobroker\GLT\node_modules\iobroker.innogy-smarthome\main.js:100:39
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at SmartHome.init (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\lib\smarthome\index.js:88:17)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at SmartHome._location (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\lib\smarthome\index.js:383:28)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at Requestor.call (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\lib\requestor\index.js:48:17)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at Requestor.doRequest (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\lib\requestor\index.js:54:12)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at new Promise (C:\iobroker\GLT\node_modules\bluebird\js\release\promise.js:103:10)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at Promise._resolveFromExecutor (C:\iobroker\GLT\node_modules\bluebird\js\release\promise.js:518:18)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at Promise.cancellationExecute [as _execute] (C:\iobroker\GLT\node_modules\bluebird\js\release\debuggability.js:406:9)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at C:\iobroker\GLT\node_modules\innogy-smarthome-lib\lib\requestor\index.js:56:22
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at Object.getAuthorizationStatus (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\lib\oauth2\index.js:300:20)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at getAuthorizationStatus (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\lib\oauth2\index.js:290:9)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at C:\iobroker\GLT\node_modules\innogy-smarthome-lib\lib\requestor\index.js:58:41
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at Object.startAuthorization (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\lib\oauth2\index.js:303:20)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at startAuthorization (C:\iobroker\GLT\node_modules\innogy-smarthome-lib\lib\oauth2\index.js:187:22)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at Function.listen (C:\iobroker\GLT\node_modules\express\lib\application.js:618:24)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at Server.listen (net.js:1447:7)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at listenInCluster (net.js:1361:12)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | at Server.setupListenHandle [as _listen2] (net.js:1313:16)
innogy-smarthome.0 | 2020-06-30 12:00:29.285 | error | (3816) Error: listen EADDRINUSE: address already in use :::3000
innogy-smarthome.0 | 2020-06-30 12:00:29.284 | error | (3816) uncaught exception: listen EADDRINUSE: address already in use :::3000
innogy-smarthome.0 | 2020-06-30 12:00:29.283 | warn | (3816) DEBUG: {"server":{"_events":{},"_eventsCount":2,"_maxListeners":100,"_connections":0,"_handle":null,"_usingWorkers":false,"_workers":[],"_unref":false,"allowHalfOpen":true,"pauseOnConnect":fal
innogy-smarthome.0 | 2020-06-30 12:00:29.282 | warn | (3816) Adapter is not configured or needs reauthorization! Please go to the adapter settings and start the authorization
innogy-smarthome.0 | 2020-06-30 12:00:29.275 | warn | (3816) Adapter is still not connected to the Innogy API, restarting!
innogy-smarthome.0 | 2020-06-30 11:59:59.273 | warn | (3816) Adapter is not connected ... Will recheck in 30 seconds!

`

**Comment by JBSullivan** [comment]
Ich befürchte, das alle Innogy User die den Adapter nach der Backend Spielerei nicht stoppen, werden ihn mit Anfragen überhäufen.

""API calls quota exceeded! maximum admitted 100 per Minute.""

**Comment by jroegner** [comment]
Innogy hat die URL der API geändert:

VORHER: https://api.services-smarthome.de/AUTH/...
JETZT: https://auth.services-smarthome.de/AUTH/...

Daher wird ohne ein funktionierendes Update auf v.0.3.5 nichts mehr laufen.

**Comment by JBSullivan** [comment]
Habe gerade nachgesehen - die Änderungen scheinen in der /innogy-smarthome-lib/ richtig drin zu sein. Wie gesagt offensichtlich scheitert es an den verschärften Richtlinien von ioB das sich der Adapter nicht installieren läßt.

**Comment by Apollon77** [comment]
> verschärften Richtlinien von ioB das sich der Adapter nicht installieren läßt.

was ist hiermit gemeint?

**Comment by Slogge** [comment]
Hallo, ihr geht auf die Einstellung der Instanz und dann "start authorization" das Fenster geht auf und ihr kopiert den Link in ein neues Fenster rein. Dann ersetzt Ihr das api durch auth
Enter....schon könnt ihr die Benutzerdaten eingeben und alles läuft wie gewohnt. Zumindest bei mir und bis jetzt

**Comment by Basti-home** [comment]
Hallo, bei funktioniert es es auch so! Dankeschön.

**Comment by PommesTC** [comment]
Dein Tip hat super funtioniert! Ist zwar immer noch die alte Version aber wenigstens ist der Adapter jetzt wieder mit Innogy verbunden. Danke!!!

 
 

Gesendet: Dienstag, 30. Juni 2020 um 16:37 Uhr
Von: "Slogge" <notifications@github.com>
An: "PArns/ioBroker.innogy-smarthome" <ioBroker.innogy-smarthome@noreply.github.com>
Cc: "PommesTC" <thomas.schmitz6@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [PArns/ioBroker.innogy-smarthome] Neustes Update Funktioniert nicht (#50)


 

Hallo, ihr geht auf die Einstellung der Instanz und dann "start authorization" das Fenster geht auf und ihr kopiert den Link in ein neues Fenster rein. Dann ersetzt Ihr das api durch auth
Enter....schon könnt ihr die Benutzerdaten eingeben und alles läuft wie gewohnt. Zumindest bei mir und bis jetzt

**Comment by JBSullivan** [comment]
> > verschärften Richtlinien von ioB das sich der Adapter nicht installieren läßt.
> 
> was ist hiermit gemeint?

Mir war doch so, das im Forum was geschrieben wurde das ab Admin 3.x.x es bei, ich nenne es mal unsauber programmierten Adaptern, Rechte Probleme geben kann - oder so ähnlich.

**Comment by PArns** [comment]
Danke für die Hinweise, ich werde in den nächsten Minuten ein Update auf 0.3.6 veröffentlichen ....

**Comment by Apollon77** [comment]
> Mir war doch so, das im Forum was geschrieben wurde das ab Admin 3.x.x es bei, ich nenne es mal unsauber programmierten Adaptern, Rechte Probleme geben kann - oder so ähnlich.

Keine Ahnung was Du meinst ...

**Comment by Slogge** [comment]
bei mir geht es seit heute Nacht wieder nicht mehr. Nach einem Restart des Adapters kann es sich nicht mehr neu verbinden.

**Comment by JBSullivan** [comment]
Gerade Adapter 0.3.6 in ioB installiert und - FUNKTIONIERT - vielen Dank für deinen Einsatz !!!

Andere Frage am Rande: Lese ich das richtig, das der Innogy Adapter nur so läuft, wie er läuft, weil DU es über deinen privaten Webspace (Hoster) laufen läßt? Wenn du vielleicht irgendwann das System wechselst oder den "Stecker ziehst", wäre dann Schluss mit dem Adapter?

Gibt es unter Umständen einen anderen Weg den Adapter für so einen Fall weiterhin am Leben zu halten? Sind ja doch einige  (hundert) die den Adapter einsetzen.

**Comment by PArns** [comment]
Danke für das Update.

Nur das Authorisierungsscript läuft auf meinem Webserver. Dieses 2 Zeilen PHP Script kann ich gerne ebenfalls einmal zur Lib hochladen, jedoch ist die Consumer ID, welche zum Login und Betrieb benötigt wird, durch Innogy an meinen Webserver bzw. meine Domain gebunden.

Gerne können aber andere User einen Beitrag zum Adapter leisten, ich suche ja schon eine ganze Weile Hilfe bei der Entwicklung ;)

**Comment by PArns** [comment]
> Habe gerade nachgesehen - die Änderungen scheinen in der /innogy-smarthome-lib/ richtig drin zu sein. Wie gesagt offensichtlich scheitert es an den verschärften Richtlinien von ioB das sich der Adapter nicht installieren läßt.

Nein, ich hab vergessen die Version ebenfalls in der Versionsbeschreibung zu ändern, die ioBroker verwendet! Das kommt davon, wenn man länger schon nichts mehr für ioBroker geschrieben hat ;)
